sudo: required
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - docker
before_install:
  - docker pull pynedist/pyne-ubuntu
install:
#  - docker run pynedist/pyne-ubuntu /bin/sh -c "git clone https://github.com/pyne/pyne ; cd pyne ; python setup.py install --user -- -DMOAB_LIBRARY=/root/opt/moab/lib/libMOAB.so -DMOAB_INCLUDE_DIR=/root/opt/moab/include"
script:
  - docker run pynedist/pyne-ubuntu /bin/bash -c "git clone https://github.com/pyne/pyne ; cd pyne ; python setup.py install --user -- -DMOAB_LIBRARY=/root/opt/moab/lib/libMOAB.so -DMOAB_INCLUDE_DIR=/root/opt/moab/include"
  - docker run pynedist/pyne-ubuntu /bin/bash - c "cd pyne ; tests ; ./travis-run-tests.sh"
#  - docker run pynedist/pyne-ubuntu /bin/sh -c "cd pyne ; cd tests ; ./travis-run-tests.sh"
  # Build the pyne-amalgamation test program 
  # - git clone https://github.com/pyne/pyne-amalgamation.git
  #- cd ..
  #- python amalgamate.py
  #- mv pyne.h pyne.cpp tests/pyne-amalgamation
  #- cd tests
  #- BASE=/home/travis/miniconda make -C pyne-amalgamation


