sudo: required
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
services:
  - docker
before_install:
  - docker pull pynedist/pyne-ubuntu
install:
  - docker run pynedist/pyne-ubuntu /bin/bash -c "ls /root/opt"
  - docker run pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/ ; pwd ; git clone https://github.com/pyne/pyne ; cd pyne ; pwd ; ls /root/opt"
  - docker run pynedist/pyne-ubuntu /bin/bash -c "ls /root/opt"
  - docker run pynedist/pyne-ubuntu /bin/bash -c "ls /root/opt/pyne"
  - docker run pynedist/pyne-ubuntu /bin/bash -c "cd /root/opt/pyne"

script:
# ; cd .. ; /root/.local/bin/nuc_data_make ; cd pyne ; cd tests ; ./travis-run-tests.sh"
#  - docker run pynedist/pyne-ubuntu /bin/sh -c "cd /root/opt/pyne ; cd tests ; ./travis-run-tests.sh"
  # Build the pyne-amalgamation test program 
  # - git clone https://github.com/pyne/pyne-amalgamation.git
  #- cd ..
  #- python amalgamate.py
  #- mv pyne.h pyne.cpp tests/pyne-amalgamation
  #- cd tests
  #- BASE=/home/travis/miniconda make -C pyne-amalgamation


